var DB_MAPPINGS = {
               "Date": "date",
               "Time": "timehhmmss",
               "Temperature": "temp",
               "Humidity": "hum",
               "Dew Point Temperature": "dew",
               "Wind Speed": "wspeed",
               "": "wlatest",
               "Wind Direction": "bearing",
               "Rainfall Rate": "rrate",
               "Rainfall": "rfall",
               "Relative Air Pressure": "press",
               "Direction of Gust": "currentwdir",
               "": "beaufortnumber",
               "Windspeed Unit": "windunit",
               "Temperature Unit": "tempunitnodeg",
               "Pressure Unit": "pressunit",
               "Rain Unit": "rainunit",
               "": "windrun",
               "": "presstrendval",
               "": "rmonth",
               "": "ryear",
               "": "rfallY",
               "": "intemp",
               "": "inhum",
               "": "wchill",
               "": "temptrend",
               "": "tempTH",
               "": "TtempTH",
               "": "tempTL",
               "": "TtempTL",
               "": "windTM",
               "": "TwindTM",
               "": "wgustTM",
               "": "TwgustTM",
               "": "pressTH",
               "": "TpressTH",
               "": "pressTL",
               "": "TpressTL",
               "": "version",
               "": "build",
               "Maximum Wind Speed - gust": "wgust",
               "": "heatindex",
               "": "humidex",
               "UV Index": "UV",
               "": "ET",
               "Solar Radiation": "SolarRad",
               "": "avgbearing",
               "": "rhour",
               "": "forecastnumber",
               "": "isdaylight",
               "": "SensorContactLost",
               "": "wdir",
               "": "cloudbasevalue",
               "": "cloudbaseunit",
               "": "apptemp",
               "": "SunshineHours",
               "": "CurrentSolarMax",
               "": "IsSunny",
               "Brightness": "brightness",
               "NO2": "no2",
               "O2": "so2",
               "CO": "co",
               "H2S": "h2s",
               "O3": "o3",
               "NO": "no",
               "PM1": "pm1",
               "PM2.5": "pm2_5",
               "PM10": "pm10",
               "Absolute Pressure": "abs_press",
               "Brightness North": "bright_north",
               "Brightness East": "bright_east",
               "Brightness South": "bright_south",
               "Brightness West": "bright_west",
               "Precipitation Event": "rIs",
               "Precipitation Type": "rKind",
               "Sun Elevation": "sunElev",
               "Sun Azimuth": "sunAzimut",
               "Error last observation": "dataerror",
               "Wind Chill Temperature": "windchill_temp",
               "Rainfall Absolute": "rfall_abs",
               "Air Pressure": "air_pressure",
               "Validity Gas Measure": "validity_gas_meas",
               "Air Quality Index": "air_quality",
               "Air Quality Index Criteria": "air_quality_crit",
}


var db_features = ["id","wspeed","windunit","bearing","temp","tempunitnodeg","hum","dew","press","pressunit","rrate","rfall","rainunit",
                    "date","timehhmmss","wgust","SolarRad","UV","pm1","pm10","pm2_5","o3","no2","so2","co","h2s","no","brightness",
                    "abs_press","bright_north","bright_east","bright_south","bright_west","rIs","rKind","sunElev","sunAzimut","dataerror",
                    "currentwdir","windchill_temp","rfall_abs","air_pressure","validity_gas_meas","air_quality","air_quality_crit"]


var db_features_1st_row = [37584,0.7,"m/s",351.4,13.1,"°C",75.3,8.9,1025.08,"hPA",0,0,"mm/d",20230605,080909,0,153.1,1,0.8,7,4.4,17.9,20.6,0,6.4,0,29.4,12309,1023.51,10.5,12.3,11.8,11.1,0,0,41.5,111.5,0,0,null,26.585,1023.1,1,19,2]